/**
 * Localized strings for punched-memory.
 *
 * The extension itself is authored in English, but anything that ends up
 * written into pi.md or surfaced in the TUI in the user's language is
 * looked up here. Add new locales by extending the table.
 *
 * The "key" is the English version; values are translations. When a
 * translation is missing we fall back to English.
 */

import type { LanguageCode } from "./config.js";

export type StringKey = keyof typeof STRINGS_EN;

export const SUPPORTED_LANGUAGES: { code: LanguageCode; label: string; flag: string }[] = [
	{ code: "en", label: "English", flag: "🇬🇧" },
	{ code: "es", label: "Español", flag: "🇪🇸" },
	{ code: "fr", label: "Français", flag: "🇫🇷" },
	{ code: "de", label: "Deutsch", flag: "🇩🇪" },
	{ code: "it", label: "Italiano", flag: "🇮🇹" },
	{ code: "pt", label: "Português", flag: "🇵🇹" },
	{ code: "ja", label: "日本語", flag: "🇯🇵" },
	{ code: "zh", label: "中文", flag: "🇨🇳" },
	{ code: "ru", label: "Русский", flag: "🇷🇺" },
];

const STRINGS_EN = {
	// pi.md section headings
	hdr_project: "🪡 pi.md — Project Memory",
	hdr_intro: (project: string) =>
		`Persistent project memory generated by \`punched-memory\`.\nThis file is **private** — it must never be committed to git or shared publicly.`,
	hdr_scope: "📋 Project Scope",
	hdr_goals: "### Goals",
	hdr_non_goals: "### Non-goals",
	hdr_stack: "🏗️ Architecture & Stack",
	hdr_tech_stack: "### Tech Stack",
	hdr_components: "### Key Components",
	hdr_decisions: "🧠 Decisions Log",
	hdr_gotchas: "⚠️ Gotchas & Pitfalls",
	hdr_todos: "✅ Tasks & TODO Checklist",
	hdr_todos_pending: "### Pending",
	hdr_todos_done: "### Done",
	hdr_sessions: "📝 Working Session Log",
	hdr_session: (id: string, from: string, to: string) => `### 🪡 Session ${id} — ${from} → ${to}`,
	hdr_session_title: (title: string) => `**Title:** ${title}`,
	hdr_session_summary: "**Summary:**",
	hdr_session_decisions: "#### Decisions made this session",
	hdr_session_files: "#### Files touched",
	hdr_session_questions: "#### Open questions",

	// entry types
	entry_decision: "Decision",
	entry_gotcha: "Gotcha",
	entry_task: "Task",
	entry_done: "Done",
	entry_note: "Note",
	entry_question: "Open question",

	// TUI labels
	ui_status_on: "🪡 (on)",
	ui_status_off: "🪡 off",
	ui_banner_title: "🪡 punched-memory",
	ui_recall_title: "🪡 Previous session(s) detected",
	ui_recall_summary: (n: number, project: string) =>
		`${n} previous session${n === 1 ? "" : "s"} recorded for this project (${project}).`,
	ui_git_title: "🪡 Git repository detected",
	ui_git_msg: "Add `pi.md` (and `.punched-memory.json`) to `.gitignore` so it never gets committed?",
	ui_init_title: "🪡 Create pi.md?",
	ui_init_msg: "No pi.md found in this directory. Initialize one now?",
	ui_save_ok: "🪡 punched: pi.md updated",
	ui_save_err: "🪡 punched: failed to update pi.md",
	ui_disabled: "🪡 punched is disabled. Run `/punched-memory config` to enable.",
	ui_config_title: "🪡 punched-memory — Configuration",
	ui_config_changed: "🪡 punched: settings saved",
	ui_main_title: "🪡 punched-memory",
	ui_forget_title: "🪡 Forget pi.md?",
	ui_forget_msg: "This permanently deletes pi.md (and its session history). Continue?",

	// commands help
	cmd_help_main: "punched-memory — persistent project memory",
	cmd_help_sub:
		"  /punched-memory                open the main menu\n" +
		"  /punched-memory config         open the configuration menu\n" +
		"  /punched-memory status         show pi.md & session info\n" +
		"  /punched-memory session        open the recall view (browse previous sessions)\n" +
		"  /punched-memory recall         alias for 'session'\n" +
		"  /punched-memory log <note>     append a free-form note to pi.md\n" +
		"  /punched-memory language <c>   set language (e.g. es, en, auto)\n" +
		"  /punched-memory forget         delete pi.md (after confirmation)\n\n" +
		"By default the extension does NOT auto-prompt for recall on session start.\n" +
		"Enable it in /punched-memory config → 'Recall prompt' to be asked automatically.",

	// tool names & descriptions
	tool_log_name: "punched_log",
	tool_log_desc:
		"Append a structured entry to pi.md (project memory). Use it for decisions, gotchas, tasks, notes and open questions.",
	tool_todo_name: "punched_todo",
	tool_todo_desc: "Manage the project TODO checklist in pi.md (add / toggle / clear).",
	tool_session_name: "punched_session",
	tool_session_desc:
		"Update the current working session summary in pi.md. Call this at meaningful checkpoints and at the end of a session.",
	tool_recall_name: "punched_recall",
	tool_recall_desc: "Read the project memory (pi.md) for this directory so you can recover context between sessions.",

	// log
	log_session_started: "session started",
	log_session_ended: "session ended",
};

type Strings = typeof STRINGS_EN;

const STRINGS_ES: Partial<Strings> = {
	hdr_project: "🪡 pi.md — Memoria del Proyecto",
	hdr_intro: (project: string) =>
		`Memoria persistente del proyecto generada por \`punched-memory\`.\nEste archivo es **privado** — nunca debe subirse a git ni compartirse públicamente.`,
	hdr_scope: "📋 Alcance del Proyecto",
	hdr_goals: "### Objetivos",
	hdr_non_goals: "### Fuera de alcance",
	hdr_stack: "🏗️ Arquitectura y Stack",
	hdr_tech_stack: "### Stack Tecnológico",
	hdr_components: "### Componentes Clave",
	hdr_decisions: "🧠 Registro de Decisiones",
	hdr_gotchas: "⚠️ Trampas y Gotchas",
	hdr_todos: "✅ Tareas y Checklist TODO",
	hdr_todos_pending: "### Pendientes",
	hdr_todos_done: "### Completadas",
	hdr_sessions: "📝 Registro de Sesiones de Trabajo",
	hdr_session: (id: string, from: string, to: string) => `### 🪡 Sesión ${id} — ${from} → ${to}`,
	hdr_session_title: (title: string) => `**Título:** ${title}`,
	hdr_session_summary: "**Resumen:**",
	hdr_session_decisions: "#### Decisiones tomadas en esta sesión",
	hdr_session_files: "#### Archivos tocados",
	hdr_session_questions: "#### Preguntas abiertas",

	entry_decision: "Decisión",
	entry_gotcha: "Gotcha",
	entry_task: "Tarea",
	entry_done: "Hecho",
	entry_note: "Nota",
	entry_question: "Pregunta abierta",

	ui_status_on: "🪡 (on)",
	ui_status_off: "🪡 off",
	ui_banner_title: "🪡 punched-memory",
	ui_recall_title: "🪡 Sesión(es) anterior(es) detectada(s)",
	ui_recall_summary: (n: number, project: string) =>
		`${n} sesión(es) anterior(es) registrada(s) para este proyecto (${project}).`,
	ui_git_title: "🪡 Repositorio git detectado",
	ui_git_msg: "¿Añadir `pi.md` (y `.punched-memory.json`) a `.gitignore` para que nunca se suba?",
	ui_init_title: "¿Crear pi.md?",
	ui_init_msg: "No se encontró pi.md en este directorio. ¿Inicializarlo ahora?",
	ui_save_ok: "🪡 punched: pi.md actualizado",
	ui_save_err: "🪡 punched: error al actualizar pi.md",
	ui_disabled: "🪡 punched está desactivado. Ejecuta `/punched-memory config` para activarlo.",
	ui_config_title: "🪡 punched-memory — Configuración",
	ui_config_changed: "🪡 punched: ajustes guardados",
	ui_main_title: "🪡 punched-memory",
	ui_forget_title: "¿Olvidar pi.md?",
	ui_forget_msg: "Esto borra permanentemente pi.md (y su historial de sesiones). ¿Continuar?",

	cmd_help_main: "punched-memory — memoria persistente del proyecto",
	cmd_help_sub:
		"  /punched-memory                abre el menú principal\n" +
		"  /punched-memory config         abre el menú de configuración\n" +
		"  /punched-memory status         muestra info de pi.md y sesiones\n" +
		"  /punched-memory session        abre el visualizador de sesiones anteriores\n" +
		"  /punched-memory recall         alias de 'session'\n" +
		"  /punched-memory log <nota>     añade una nota libre a pi.md\n" +
		"  /punched-memory language <c>   cambia el idioma (es, en, auto)\n" +
		"  /punched-memory forget         borra pi.md (con confirmación)\n\n" +
		"Por defecto la extensión NO pregunta al inicio de cada sesión para recuperar.\n" +
		"Actívalo en /punched-memory config → 'Recall prompt' si quieres que lo pregunte automáticamente.",

	tool_log_name: "punched_log",
	tool_log_desc:
		"Añade una entrada estructurada a pi.md (memoria del proyecto). Úsala para decisiones, gotchas, tareas, notas y preguntas abiertas.",
	tool_todo_name: "punched_todo",
	tool_todo_desc: "Gestiona la checklist TODO del proyecto en pi.md (añadir / marcar / limpiar).",
	tool_session_name: "punched_session",
	tool_session_desc:
		"Actualiza el resumen de la sesión actual en pi.md. Llámala en puntos clave y al final de la sesión.",
	tool_recall_name: "punched_recall",
	tool_recall_desc: "Lee la memoria del proyecto (pi.md) en este directorio para recuperar contexto entre sesiones.",

	log_session_started: "sesión iniciada",
	log_session_ended: "sesión finalizada",
};

const STRINGS_FR: Partial<Strings> = {
	hdr_project: "🪡 pi.md — Mémoire du Projet",
	hdr_scope: "📋 Périmètre du Projet",
	hdr_goals: "### Objectifs",
	hdr_non_goals: "### Hors périmètre",
	hdr_stack: "🏗️ Architecture & Stack",
	hdr_tech_stack: "### Stack Technique",
	hdr_components: "### Composants Clés",
	hdr_decisions: "🧠 Journal de Décisions",
	hdr_gotchas: "⚠️ Pièges & Gotchas",
	hdr_todos: "✅ Tâches & Checklist TODO",
	hdr_todos_pending: "### En attente",
	hdr_todos_done: "### Terminées",
	hdr_sessions: "📝 Journal des Sessions de Travail",
};

const TABLES: Partial<Record<LanguageCode, Partial<Strings>>> = {
	en: STRINGS_EN,
	es: STRINGS_ES,
	fr: STRINGS_FR,
};

export function t(lang: LanguageCode, key: StringKey, ...args: unknown[]): string {
	const table = TABLES[lang] ?? STRINGS_EN;
	const fn = (table[key] ?? STRINGS_EN[key]) as (...a: unknown[]) => string;
	return typeof fn === "function" ? fn(...args) : String(fn);
}

/** A short, human-readable name for the language (always available). */
export function languageName(code: LanguageCode): string {
	const found = SUPPORTED_LANGUAGES.find((l) => l.code === code);
	return found ? `${found.flag} ${found.label}` : code.toUpperCase();
}